### ISSUE TITLE
[CRASH] ...

### ISSUE THREAD

**Issue by LMW1327** [MundM2007/Ultimate-Progression#12]
When I try and launch the game in realistic world gen mode (I have not explored other generation options, and in creative, I can get to joining world and then the game will not continue, and I get a CTD, without actually joining the world (as in I do not interact with any elements in the world itself). No mods have been added to the pack

Any advice would be welcome, as this looks a promising pack,
Please find my crash reports attached
[crash-2022-02-25_23.40.11-server.txt](https://github.com/MundM2007/Ultimate-Progression/files/8145679/crash-2022-02-25_23.40.11-server.txt)
[crash-2022-02-26_01.42.11-server.txt](https://github.com/MundM2007/Ultimate-Progression/files/8145680/crash-2022-02-26_01.42.11-server.txt)

**Comment by MundM2007** [comment]
Sorry for taking so long to answer, For me this seems to work, maybe try using the Biomes O Plenty World Preset and/or reinstalling the modpack again.
