### ISSUE TITLE
[BUG] No crafting recipes in JEI

### ISSUE THREAD

**Issue by zzeerg** [MundM2007/Ultimate-Progression#13]
**Describe the bug**
No recipes in jei, only 204 lists in crafting table
![bug](https://user-images.githubusercontent.com/100779868/156374627-ee2d5309-2779-4472-a21f-a23c6398236b.png)

**Versions:**
- Modpack version: 0.5.3
- OS: Windows 10

**Additional context**
Only Added OptiFine_1.16.5_HD_U_G8.jar

**Comment by zzeerg** [comment]
It not working, recipes don't work only in multiplayer (LAN)

**Comment by MundM2007** [comment]
Is this Singleplayer?

**Comment by zzeerg** [comment]
Not working only LAN, i tested it now

**Comment by MundM2007** [comment]
If you are playing LAn it could be that it doesn't work, but there is nothing i can do about that then...
