### ISSUE TITLE
None of the colossal chest parts are craftable[BUG] ...

### ISSUE THREAD

**Issue by Truthteller654** [MundM2007/Ultimate-Progression#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
- Modpack version:
- OS:
- Server?:

**Additional context**
Add any other context about the problem here. [e.g. Own mods added?]
![pixelmon typlosion](https://user-images.githubusercontent.com/101965529/159151966-042cf328-2e7f-4992-9260-eb736371bec3.png)

**Comment by MundM2007** [comment]
This has been disabled because it causes Lag if you want to enable it delete the ServerOnlyScripts.zs file in the Scripts folder. I will add this Info to the README.txt in the next update...
