### ISSUE TITLE
Low performance on high end pc with Create mod[QUESTION]

### ISSUE THREAD

**Issue by kazoth** [MundM2007/Ultimate-Progression#16]
**Question**
...
The windmill from create destroys my performance, the same thing happens with the immersive engineering one but not nearly as bad.

**Comment by MundM2007** [comment]
How much does it decrease fps? Did you add any extra mods?

**Comment by johnson32414** [comment]
> How much does it decrease fps? Did you add any extra mods?

im not the modpack creator or anything but personally i found that adding optifine helped drastically. sadly you got to add it yourself since the creator of optifine for some reason made it so people arent allowed to have it in packs automatically
