### ISSUE TITLE
[CRASH] ultimate progression

### ISSUE THREAD

**Issue by ferenckala** [MundM2007/Ultimate-Progression#17]
**Describe the Crash**
A clear and concise description of when the Crash happens

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/104081751/164247813-78e502bc-7ccf-4d2b-bd78-0268acd18309.png)

Connection lost
Internal Exception: io.netty.handler.codec.EncoderException: Java.lang.NullPointerException: Registry Object not present: minecraft:milk

**Versions (please complete the following information):**
- Modpack version: 0,6,1a
- OS:
- Server?: 0,6,1a

**Additional context**
we have been playing on our server for over 3 days and without problems and since our server so started today we can not access our server

**Crash Report / log**
[20.04 13:45:48] [Disconnect] ferenckala has disconnected, reasonInternal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Registry Object not present: minecraft:milk
[20.04 13:45:48] [Server] [Server thread/INFO] [minecraft/DedicatedServer]: ferenckala left the game

**Comment by MundM2007** [comment]
Please upload the entire Crash log and/or log. Did you try to restart your server again?

**Comment by ferenckala** [comment]
thx is it op and run agin
