### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by ferenckala** [MundM2007/Ultimate-Progression#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/104081751/164936493-6999b680-5c82-44a6-9bbb-219e9b682028.png)
![image](https://user-images.githubusercontent.com/104081751/164936509-0adf8bde-5187-45df-8ef6-4590f8e5503e.png)

**Versions (please complete the following information):**
- Modpack version: 0,6,1a
- OS:
- Server?: ferenckala's Minecraft Server

**Additional context**

the task is 100% but it will not be approved so you can move on with the next ones

**Comment by MundM2007** [comment]
This happens when you enter the Dimension before you unlock the Quest, this is a Bug from ftbquests and there is nothing i can do about this. I already created a Bug Report in the ftbquest repository a few montags ago.

**Comment by ferenckala** [comment]
ok thx

**Comment by ferenckala** [comment]
is it ern comand I can write to get the tasks done
