### ISSUE TITLE
Server Download Unusable

### ISSUE THREAD

**Issue by xAlionaHeartx** [MundM2007/Ultimate-Progression#2]
I just recently downloaded your server file from the curseforge site and am having a very hard time getting it to run properly. I've tried the simple copy/paste, as well as manually installing all of it and am still getting consistent crashes. Any help would be greatly appreciated.

Ive attached the crash report below as well, in case that would help.
[2021-12-07-1.log](https://github.com/MundM2007/Ultimate-Progression/files/7665584/2021-12-07-1.log)

**Comment by MundM2007** [comment]
Found the error pretty cickly... you are using forge version 36.2.19 you need to use the one included in the server files so 36.2.4
