### ISSUE TITLE
[CRASH] Launching game and once mods are loaded, it crashes

### ISSUE THREAD

**Issue by Clawsoffury** [MundM2007/Ultimate-Progression#22]
**Describe the Crash**
Once all mods are loaded up, java stops responding.

**To Reproduce**
1. Go to modpack
2. Click "play"
3. Allow mod to load up.
4. Once mods are loaded, screen does not change from Mojang.
5. Click once and notice pops up that it is no longer responding, and will continue to do so no matter how much time passes.

**Versions (please complete the following information):**
- Modpack Version: 0.6.5
- Server?: No

**Crash Report / log**
No crash log is generated. Java stops responding...
[Log 6_6_2022.txt](https://github.com/MundM2007/Ultimate-Progression/files/8846293/Log.6_6_2022.txt)

**Comment by MundM2007** [comment]
Do you get to the point where the game says in the bottom of screen "freezing data"?
That point always freezes and takes some time. Please don't click on the game during that time.
Also try reinstalling the modpack, the log also says that the mod FancyMenu couldn't be installed, this could potentially cause a rendering error with the main menu, so please try to reinstall adn check if the mod FancyMenu is installed, if not please add it Manually. Please tell me if this helps.
