### ISSUE TITLE
[BUG] Thermal series machines dupe glitch

### ISSUE THREAD

**Issue by Ultimate8wworrior** [MundM2007/Ultimate-Progression#26]
**Describe the bug**
ok so this is pretty busted and i found about it by mistake, if you place a phytogenic insolator (not sure if it works with other machines but im guessing it does) with an empty redprint in your off hand it will place it normally, however once you open the machine up it will give u a new one in your inventory, i cant really show it using pictures (a video would be better) but i'll try my best.

**To Reproduce**
1. have a phytogenic insolator in your main hand and a redprint in your off hand (redprint must be empty aka shift click the air)
![image](https://user-images.githubusercontent.com/85767840/182948259-62d060b9-66c5-4e5e-9bb3-a58141a39b96.png)

2. simply place the machine (put as many as you want to dupe, can be done infinitely)
![image](https://user-images.githubusercontent.com/85767840/182948540-a4f35fd9-74ba-42dc-aa9b-359255033880.png)

3. open any one of the machines you placed and somehow get back all the machines you placed while they are still there as shown here
![image](https://user-images.githubusercontent.com/85767840/182948810-b8f55465-33bb-4858-b3a0-e5a68289c98b.png)

4. do it as much as u want (I just tested it with a pulverizer and it did work so yeah, all thermal machines)

**Expected behavior**
to not dupe i guess lol, or if the redprint is empty it should not have a functionality, like it is not supposed to affect the machine anyway if it has no copied settings from a previous machine.

**Screenshots**
i put them with the steps to make it better to understand

**Versions (please complete the following information):**
- Modpack version: 1.0.2
- Server?: No

**Additional context**
nothing really, only thing i edited was the shop and im pretty sure it isn't related, also no extra mods installed or removed.

i really hope if someone can test this in their world and see if it works to make sure it isn't related to my world and share that info with me ty very much.

**Comment by MundM2007** [comment]
This dupe seems to be entirely related to thermal series. It doesn't have to do with any other Mod really. I will Test this in an extra Profile only with thermal installed. And wil Tell you If it world or Not. 
If it's a Bug to thermal only, then I'm Not sure If the Dev's will fix it though. Because they May don'tt Support 1.16 anymore (Last Update was in may)

**Comment by MundM2007** [comment]
This is a bug from thermal series only. This has nothing to do with the modpack. Will try to report this to thermal series

**Comment by Ultimate8wworrior** [comment]
Yeah figured as much, thank you for the help.

**Comment by MundM2007** [comment]
To given you an updated on this: the Bug will be fixed in thermal series next update
