### ISSUE TITLE
[CRASH] When player joins server

### ISSUE THREAD

**Issue by evilspacebunny** [MundM2007/Ultimate-Progression#28]
Server loads up fine but upon joining the server the server then crashes. Even after joining again.
Crash reports:
First attempt to join server
https://pastebin.com/eJ2ur97h
Second attempt
https://pastebin.com/G0CEtyf7
It reverts back and forth between the two errors.

- Modpack version:1.0.5
- Server?: Yes Linux based

**Comment by MundM2007** [comment]
Some Solutions that may help:
-Increase the "-Xmx4G" Argument in the Server start file (because the server currently uses only 4GB) described in step 5
-Set "max-tick-time" to "-1" in the "server.properties" file
-Try using a different Java version if possible. (for example java 8)
Hope this helps!
