### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by sharpskull2** [MundM2007/Ultimate-Progression#30]
https://github.com/starforcraft/Botany-Pots-Tiers/issues/5
**Describe the bug**
Botany Pots Tiers mod pots cause network lag for all players on a server while around the pots, the issue is worse when you have them in large quantities.
Due to the nature of how this mod creates network lag it does not affect singleplayer because it's a direct connection on the same internet. This also means that people who host a server on their own internet will not see this issue as heavily as other people playing on a hosted server.

with a few pots scattered around ping will jump up into the 2-4k ms range, with larger quantities ping will jump upwards of 10k and time you out of the server.

**To Reproduce**
1. Play on a multiplayer server that is not on your own wifi
2. Place down tiered botany pots (preferably in large quantities to see the effect more clearly and quickly)
3. Watch ping spike through the rough and the client is unable to do anything on the server

**Expected behavior**
Expect some ticking lag due to the pots, but not network lag.

**Versions (please complete the following information):**
- Modpack version: 1.0.7
- Server?: Yes (Only affects multiplayer, non-host)

**Additional context**
The mod author of Botany Pots Tiers currently has no plans to fix this bug and has said to use the 1.18 version which this issue is supposedly fixed on. I'd recommend removing this mod or finding an alternative for it because it can make playing on a server with friends unplayable.

**Comment by MundM2007** [comment]
I tested the mod, it didn't crash. Will probably make a change to it. Expect an update in around a week or so!
