### ISSUE TITLE
[QUESTION] Automate Smithing Table for Netherite Barrel?

### ISSUE THREAD

**Issue by Trnrr** [MundM2007/Ultimate-Progression#31]
**Question**
Is it possible to automate the Smithing table? I want to automate the Netherite Barrels and the only recipe involves a smithing table. When I hook that up to refined storage crafter it doesn't work. I'm wondering if there's another mod or way to accomplish this?

**Comment by MundM2007** [comment]
Sorry for not answering, but i think this is not possible
