### ISSUE TITLE
Bloodmagic quest broken

### ISSUE THREAD

**Issue by zippy36jr** [MundM2007/Ultimate-Progression#4]
The quest for visiting the blood magic dungeon does not complete once you visit the dungeon. ![image](https://user-images.githubusercontent.com/10852100/147887509-e168e606-e674-4e79-a5c6-bfe0cda7a86e.png)

**Comment by MundM2007** [comment]
It seems to be completed. This could be an Bug from ftbquests. Did you try entering the dimension again or restarted the modpack ans Thema entering the dimension again?

**Comment by zippy36jr** [comment]
Yeah we entered multiple times, we even remade the pillar and went in again, and we restarted the server but nothing seemed to make it work. We just ended up running the change progress command in admin mode.
