### ISSUE TITLE
[BUG] Tooltip placement 

### ISSUE THREAD

**Issue by TonTonAsoX** [MundM2007/Ultimate-Progression#41]
**Describe the bug**
When hovering some GUI buttons on machines (Refined Storage constructor, destructor, Mekanism Digital Miner, etc...), the tooltip who explains what's the hovered button do is not well placed.

**To Reproduce**
1. Go to GUI of Digital Miner (for example)
2. Hover the Visuals button'
4. See the placement of the tooltip

**Expected behavior**
Tooltip must be placed next to the button, not on the side of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/53052744/236204429-886916b2-3fef-4b50-aaf5-232d1e512c67.png)
![image](https://user-images.githubusercontent.com/53052744/236204497-b85a7d6a-d927-419a-b5e9-d8efd677ac59.png)

**Versions (please complete the following information):**
- Modpack version: 1.2.1
- Server?: No

**Additional context**
-

**Comment by MundM2007** [comment]
I've noticed this already a lot of times, but because i've no idea what mod is causing this and have no Idea how to fix this, I cant fix this

**Comment by katsutosh** [comment]
the mod that causes this behavior is Just Enough Calculations
After removing the mod or downgrading to version 3.8.6, the tooltips are back in the right place.
(source: https://github.com/Towdium/JustEnoughCalculation/issues/116)

**Comment by TonTonAsoX** [comment]
Ow, ok, thanks for the reply !
