### ISSUE TITLE
[QUESTION] ftbteams quests

### ISSUE THREAD

**Issue by JustLikeNone** [MundM2007/Ultimate-Progression#42]
**Question**
when i add my friend to the ftbteams party so we can share qeusts he can't recive any quests or do any?
idk why but if it a fueture in the modpack tell me

**Comment by MundM2007** [comment]
Sorry for the late reply, I have Seen this before already though I've forgotten about it.

This seems Like a really wierd error and this shouldn't happen. Try to remove your friend again and readd him using ftbteams. If this didn't fix it please Tell the exact process of adding him.

You can also try to refresh the Server Files maybe they where corrupted.
