### ISSUE TITLE
[CRASH] Server files for 1.2.3 contain client only mods

### ISSUE THREAD

**Issue by JulianVennen** [MundM2007/Ultimate-Progression#43]
**Describe the Crash**
When you attempt to start the server, it crashes due to the following client only mods:
- Embeddium
- Embeddium Extras
- Embeddium Extension
- TexTrue's Embeddium Options

**To Reproduce**
1. Download the server files from CurseForge
2. Run the forge installer
3. Attempt to start the server

**Versions (please complete the following information):**
- Modpack version: 1.2.3
- Server?: Yes

**Additional context**
No modifications to the server files have been done.

**Crash Report / log**
Log with embeddium extras: https://mclo.gs/xGKaLeA#L698

**Comment by MundM2007** [comment]
Yeah, will fix this soontm, can you try and See what Happens If you only remove embeddiumextras from the server

**Comment by MundM2007** [comment]
I'm currently uploading the new version. It will be available in approximately half an hour.
