### ISSUE TITLE
Brass Plates 

### ISSUE THREAD

**Issue by Samical** [MundM2007/Ultimate-Progression#44]
Impossible to make brass plates - 
You can't make the Brass plates without immersive immersive engineering metal press but you need the Create crafters to make the engineering blocks for the metal press and you need brass plates to make the crafters from Create. This stops all progression as you can't get the brass plates to make the things needed to make the brass plates.

**Comment by MundM2007** [comment]
Can't you use the create press? Make Sure to Check the Brass Plate from Emendatus Enigmatica

**Comment by MundM2007** [comment]
yup, have verified obtainable via create pressing
