### ISSUE TITLE
Ghost Blocks Everywhere

### ISSUE THREAD

**Issue by jona69420** [MundM2007/Ultimate-Progression#6]
i was playing on my friend's server hosted on server.pro, and all the players are having the same glitch. if someone tries to make a multiblock from immersive engineering, like arc furnace, then it forms but it does not transform into the model until i re-join OR go to an other dimension and back. this also happens with building gadgets and building wands except if i click on the block it gets 
fixed if i right or left click on it and it only happens with not vanilla blocks.

![2022-01-15_19 10 57](https://user-images.githubusercontent.com/91335746/149633430-2dc7520f-9389-40ad-b6d8-94e79fc53357.png)

![2022-01-15_19 11 32](https://user-images.githubusercontent.com/91335746/149633336-56e07735-15c7-47b4-9b38-d57b542c5e83.png)

we tried stuff like the antighost mod https://www.curseforge.com/minecraft/mc-mods/antighost antighost-1.16.4-forge35.0.7-1.1.2.jar
and removing the chunk animator mod but nothing worked.

this does not occour in singleplayer

**Comment by DragarX** [comment]
I had this issue with crest contraptions.
Installed this mod on server and clients and it fixed all my ghost blocks. 
[Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) 
Maybe it should be included with the pack?
