### ISSUE TITLE
the game crashes

### ISSUE THREAD

**Issue by YunChea** [MundM2007/Ultimate-Progression#9]
When I sink (Cooking for Blockheadsd's) with Cyclic's Fluid Cable, the game crashes
[crash-2022-02-17_18.51.51-client.txt](https://github.com/MundM2007/Ultimate-Progression/files/8088144/crash-2022-02-17_18.51.51-client.txt)

**Comment by YunChea** [comment]
I crash and quit when I join the game, how can I fix this?

**Comment by MundM2007** [comment]
maybe try not using cyclic pipes...
